version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/rails-api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - volume-db:/var/lib/postgresql/data
volumes:
  volume-db:
    driver: local
